version: 2
jobs:
  ios:
    macos:
      xcode: "10.1.0"
    steps:
      - checkout
      - run:
          name: Build and test
          command: xcodebuild -scheme "CacheMeIfYouCan" -project "CacheMeIfYouCan/CacheMeIfYouCan.xcodeproj" -destination 'platform=iOS Simulator,name=iPhone 7' build test
workflows:
  version: 2
  build_and_test:
    jobs:
      - ios
